name: "Continuous Integration"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use oxr463/setup-leiningen
      uses: ./
      with:
        exec: |
          lein uberjar
          cp "$(find . -name '*.jar')" .
